--- #YAML:1.0
name: XML-Genx
version: 0.20
author:
  - Dominic Mitchell <cpan(at)happygiraffe.net>
abstract: A simple, correct XML writer
license: bsd
generated_by: Module::Build version 0.2611, without YAML.pm
